

#*****************  Api Deployment  *****************#

  apiGatewayDeployment:
    Type: "AWS::ApiGateway::Deployment"
    DependsOn:   
      - "CumApiGateway"
      - "ApiGatewayMethodclientvariantkeyInvoke"
      - "ApiGatewayMethoddisplaymessageInvoke"
      - "ApiGatewayMethoddiscoverInvoke"
      - "ApiGatewayMethodcreatekeykeyInvoke"
      - "ApiGatewayMethoddeletekeykeyInvoke"
      - "ApiGatewayMethodgetkeykeyInvoke"
      - "ApiGatewayMethoduserkeystorekeypostInvoke"
      - "ApiGatewayMethoduserkeystorekeygetInvoke"
      - "ApiGatewayMethoduserkeystorekeydeleteInvoke"  
    Properties:
      RestApiId: !Ref "CumApiGateway"
      StageName: !Ref "CumApiGatewayStageName"
      StageDescription:
        MethodSettings:
        - DataTraceEnabled: true
          HttpMethod: "*"
          LoggingLevel: INFO
          MetricsEnabled: true
          ResourcePath: "/*"

