#Inputs:
#  LambdaInvokeID : CumLambdaApiGatewayInvoke
#  FunctionName : outClientConfigUpdateReceptor
#  ApiGatewayMethodID : CumApiGatewayMethodIngestJournalbg


  $LambdaInvokeID$:
    Type: AWS::Lambda::Permission
    DependsOn:
      - "$ApiGatewayMethodID$"
    Properties:
      Action: lambda:invokeFunction
      FunctionName: '$FunctionName$:live'
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
        - ''
        - - 'arn:aws:execute-api:'
          - Ref: AWS::Region
          - ":"
          - Ref: AWS::AccountId
          - ":"
          - Ref: CumApiGateway
          - "/*"
