#Inputs:
#  ResourceID
#  PathPart
#  ParentResourceID

  $ResourceID$:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref "CumApiGateway" 
      ParentId: !Ref "$ParentResourceID$" 
      PathPart: "$PathPart$"

