

#*****************  Api Deployment  *****************#

  apiGatewayDeployment:
    Type: "AWS::ApiGateway::Deployment"
    DependsOn:   
      - "CumApiGateway" 
      - "ApiGatewayMethodblengppreferencesupdateInvoke"    
      - "ApiGatewayMethodbundlenotifupdateInvoke"    
      - "ApiGatewayMethoddiscovernotifupdateInvoke"    
      - "ApiGatewayMethodclientblengpnotifupdateInvoke"    
      - "ApiGatewayMethodpreferencesremoveallInvoke" 
    Properties:
      RestApiId: !Ref "CumApiGateway"
      StageName: !Ref "CumApiGatewayStageName"
      StageDescription:
        MethodSettings:
        - DataTraceEnabled: true
          HttpMethod: "*"
          LoggingLevel: INFO
          MetricsEnabled: true
          ResourcePath: "/*"
